services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    depends_on:
      - zookeeper

  postgres:
    image: timescale/timescaledb:latest-pg16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: toxicflow
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  ingestor:
    build:
      context: ../ingestion
      args:
        VERSION: dev
    image: tofd/ingestor:dev
    container_name: tofd-ingestor
    restart: unless-stopped
    depends_on:
      - kafka
    environment:
      BROKER: kafka
      KAFKA_BROKERS: kafka:9092
      FEED_MODE: csv
      CSV_PATH: /data/sample_binance_trades.csv
      CSV_SPEED: "50"
      CSV_LOOP: "true"
      LOG_FORMAT: json
      STATS_EVERY: 15s
    volumes:
      - ../data:/data:ro
    ports:
      - "9090:9090"

  processing:
    build:
      context: ../processing
    image: tofd/processing:dev
    container_name: tofd-processing
    restart: unless-stopped
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092
      KAFKA_GROUP_ID: processing-group
      INPUT_TOPIC: trades.raw
      OUTPUT_TOPIC: trades.normalized
      NUM_WORKERS: "4"

  scorer:
    build:
      context: ../scoring
    image: tofd/scorer:dev
    container_name: tofd-scorer
    restart: unless-stopped
    depends_on:
      - kafka
      - postgres
    environment:
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: trades.normalized
      KAFKA_ALERTS_TOPIC: trades.alerts
      KAFKA_GROUP_ID: tofd-scorer
      PG_DSN: postgresql://postgres:devpassword@postgres:5432/toxicflow

  dashboard:
    build:
      context: ../dashboard
    image: tofd/dashboard:dev
    volumes:
      - ../dashboard:/app
    container_name: tofd-dashboard
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_started
      kafka:
        condition: service_started
    environment:
      PG_DSN: postgresql://postgres:devpassword@postgres:5432/toxicflow
      KAFKA_BROKERS: kafka:9092
      JWT_SECRET: "9a8f4c2e1b7d3f6a0e5c8b2f4a1d3e6f9c8b7a6f5e4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1e0d9c8b7a6f5e4d3c2b1a0f9e8d7c6b5a4f3e2d"
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "password"
    ports:
      - "8000:8000"
